In [9]:
from sklearn.tree import DecisionTreeClassifier

def classify(X_train, y_train):
    clf = DecisionTreeClassifier()
    clf.fit(X_train, y_train)
    return clf
    

In [10]:
features_train = [[0, 0], [1, 1]]
labels_train = [0,1]

clf = classify(features_train, labels_train)

In [11]:
clf.predict([2,2])

C:\Anaconda3\envs\udacityenv\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [12]:
clf.predict_proba([[2,2]])

array([[ 0.,  1.]])

In [17]:
import numpy as np
temp = np.array([2,2]).reshape((1, -1))   # Some crazy way to solve the warning. Why the folks at Slearn at getting too comfortable
clf.predict(temp)

array([1])

In [7]:
from math import log 

In [10]:
p1=2.0/3
p2=1.0/3
-1*p1*log(p1,2)-p2*log(p2,2)

0.9182958340544896