# Numpy

In [5]:
import numpy as np
numbers = [1, 2, 3, 4, 5]
print(np.mean(numbers))
print(np.median(numbers))
print(np.std(numbers)) #This is the standard deviation

3.0
3.0
1.41421356237


Numpy Arraies are optimize to run faster

In [7]:
array = np.array(numbers, float)
print (array)

[ 1.  2.  3.  4.  5.]


Numpy Arraies can be two dimensional

In [9]:
array = np.array([[1,2,3], [4,5,6]], float)
print (array)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [14]:
num = [1, 2, 3, 4, 5]
ray = np.array( num, float)
print (num[3])
print (num[:4])
print (num[:5])
print (num[2:])

4
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[3, 4, 5]


In [17]:
ray = np.array([[1,2,3], [4,5,6]], float)

print (ray[1][2])
print (ray[1][1])
print (ray[:, 2])

6.0
5.0
[ 3.  6.]


Array arithmetics

In [22]:
ray1 = np.array([1, 2, 3], float)
ray2 = np.array([5, 2, 6], float)

print (ray1+ray2)
print (ray1*ray2)
print (np.mean(ray1))
print(np.dot(ray1, ray2))

[ 6.  4.  9.]
[  5.   4.  18.]
2.0
27.0
