In [1]:
import numpy as np 

In [24]:
lis1=[1, 2, 4, 2, 5, 3, 8]
lis2 = [2, 3, 5, 32, 32,1, 21]

In [25]:
np.mean(lis1)

3.5714285714285716

In [26]:
np.std(lis1)

2.1946130708196026

In [27]:
np.median(lis1)

3.0

In [28]:
np.array(lis1,float)

array([ 1.,  2.,  4.,  2.,  5.,  3.,  8.])

In [30]:
k=np.array([lis1, lis2],float)

In [31]:
k

array([[  1.,   2.,   4.,   2.,   5.,   3.,   8.],
       [  2.,   3.,   5.,  32.,  32.,   1.,  21.]])

In [32]:
k[1, :]

array([  2.,   3.,   5.,  32.,  32.,   1.,  21.])

In [33]:
k[:, 3]

array([  2.,  32.])

In [34]:
m=np.array([lis2, lis1], float)

In [35]:
m

array([[  2.,   3.,   5.,  32.,  32.,   1.,  21.],
       [  1.,   2.,   4.,   2.,   5.,   3.,   8.]])

In [36]:
k*m

array([[   2.,    6.,   20.,   64.,  160.,    3.,  168.],
       [   2.,    6.,   20.,   64.,  160.,    3.,  168.]])

In [38]:
k-3*m

array([[ -5.,  -7., -11., -94., -91.,   0., -55.],
       [ -1.,  -3.,  -7.,  26.,  17.,  -8.,  -3.]])

In [39]:
np.dot(lis1, lis2)

423